version: "3"
services:
  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=monadmonad
      - POSTGRES_DB=coin
    ports:
      - 5432:5432


